### ISSUE TITLE
[Bug] Fuzzy skin default params are far to high

### ISSUE THREAD

**Issue by DatenThielt** [mjonuschat/PrusaSlicer-Profiles#1]
I believe on all profile the fuzzy skin is set far to high,

![image](https://github.com/mjonuschat/PrusaSlicer-Profiles/assets/4466326/8913fc50-2bb3-4147-8a72-1d3b22990925)

The values should be much lower,  (Thickness 0.2, Skin point distance 0.4) 

Other than that, cant wait for my current print to finish to test out these!

**Comment by mjonuschat** [comment]
Default PrusaSlicer values (0.3 / 0.8mm) have been restored in #2
