### ISSUE TITLE
Is it ok to use for non CoreXY ?

### ISSUE THREAD

**Issue by Trilis29** [mjonuschat/PrusaSlicer-Profiles#3]

**Comment by mjonuschat** [comment]
Technically there's nothing preventing the use of the on any other kind of printer. Just keep in mind that this profile's speeds/acceleration values are tuned for linear rail CoreXY machines and might be too much for some printers.

**Comment by bassamanator** [comment]
Absolutely fine to use on a non-coreXY. I use these profiles at 'full capacity' on my Sovol SV06. Make sure your machine is well tuned and that you've figured out your max accel and speed using the Ellis `test_speed` macro.
